"""initial migration

Revision ID: 156fad2bc11d
Revises: 
Create Date: 2025-07-14 14:39:16.174390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '156fad2bc11d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('election_supervisors')
    op.drop_table('supervisors')
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('end_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('vote_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
        batch_op.create_unique_constraint('unique_vote', ['student_id', 'election_id', 'position_id'])

    with op.batch_alter_table('voting_sessions', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voting_sessions', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_vote', type_='unique')
        batch_op.alter_column('vote_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('end_users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    op.create_table('supervisors',
    sa.Column('supervisor_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('supervisor_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('election_supervisors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('election_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supervisor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('election_supervisors_ibfk_1')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisors.supervisor_id'], name=op.f('election_supervisors_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
