"""Add created_at to elections

Revision ID: 30b178bbdb54
Revises: 54dccfb5d84c
Create Date: 2025-07-21 09:50:46.561885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b178bbdb54'
down_revision = '54dccfb5d84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
