"""Fix table names and FKs

Revision ID: 54dccfb5d84c
Revises: fa4fb612fbff
Create Date: 2025-07-21 09:38:34.476792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54dccfb5d84c'
down_revision = 'fa4fb612fbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voters',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.Integer(), nullable=True))
        batch_op.drop_column('vote_count')
        batch_op.drop_column('manifesto')

    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('status')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manifesto', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('vote_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.drop_column('votes')

    op.drop_table('voters')
    # ### end Alembic commands ###
