"""Add role to Enduser 

Revision ID: fa4fb612fbff
Revises: bcc6e9ea8c24
Create Date: 2025-07-16 10:14:23.144419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4fb612fbff'
down_revision = 'bcc6e9ea8c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('end_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('end_users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
